security:
 sessions: NEVER
---
spring:
 data:
  mongodb:
   host: localhost
   database: optosoft-dev
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
